import {StyleSheet} from 'react-native';
import {
  Colors,
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  topContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.gray,
    height: verticalScale(250),
  },
  headerText: {
    fontSize: moderateScale(45),
    color: Colors.black,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  bottomContainer: {
    paddingVertical: verticalScale(20),
  },
  fieldText: {
    fontSize: moderateScale(15),
    color: Colors.black,
    fontWeight: '500',
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
  },
  emailInput: {
    fontSize: moderateScale(16),
    color: Colors.black,
    fontWeight: '400',
    padding: moderateScale(8),
    borderWidth: moderateScale(1),
    borderColor: Colors.gray,
    borderRadius: moderateScale(5),
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
  },
  focusedEmailInput: {
    fontSize: moderateScale(16),
    color: Colors.black,
    fontWeight: '400',
    padding: moderateScale(8),
    borderWidth: moderateScale(1),
    borderColor: Colors.red,
    borderRadius: moderateScale(5),
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
  },
  error: {
    fontSize: moderateScale(13),
    color: Colors.red,
    fontWeight: '500',
    marginHorizontal: horizontalScale(20),
  },
  forgotPassword: {
    fontSize: moderateScale(14),
    color: Colors.darkGray,
    fontWeight: '500',
    alignSelf: 'flex-end',
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
  },
  signInButton: {
    backgroundColor: Colors.lightGreen,
    padding: moderateScale(8),
    borderRadius: moderateScale(5),
    alignSelf: 'flex-end',
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
  },
  signInText: {
    fontSize: moderateScale(15),
    color: Colors.white,
    fontWeight: '500',
  },
  signupContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    alignSelf: 'flex-end',
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
  },
  notMember: {
    fontSize: moderateScale(14),
    color: Colors.black,
    fontWeight: '600',
  },
  signupFree: {
    fontSize: moderateScale(14),
    color: Colors.black,
    fontWeight: '400',
    textDecorationLine: 'underline',
    marginHorizontal: horizontalScale(5),
  },
  passwordContainer: {
    borderWidth: moderateScale(1),
    borderColor: Colors.gray,
    borderRadius: moderateScale(5),
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  focusedPasswordContainer: {
    borderWidth: moderateScale(1),
    borderColor: Colors.red,
    borderRadius: moderateScale(5),
    marginHorizontal: horizontalScale(20),
    marginVertical: verticalScale(5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordInput: {
    flex: 1,
    fontSize: moderateScale(16),
    color: Colors.black,
    fontWeight: '400',
    padding: moderateScale(8),
  },
  passwordIcon: {
    margin: moderateScale(8),
    height: moderateScale(20),
    width: moderateScale(20),
    resizeMode: 'contain',
  },
  orSignInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginVertical: verticalScale(40),
  },
  signInBar: {
    flex: 1,
    height: verticalScale(1),
    backgroundColor: Colors.darkGray,
    marginHorizontal: horizontalScale(20),
  },
  orSignInText: {
    fontSize: moderateScale(14),
    color: Colors.black,
    fontWeight: '400',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialImage: {
    height: moderateScale(50),
    width: moderateScale(50),
    resizeMode: 'contain',
    margin: moderateScale(5),
  },
  guestText: {
    fontSize: moderateScale(14),
    color: Colors.darkGray,
    fontWeight: '400',
    alignSelf: 'flex-end',
    margin: moderateScale(20),
  },
});
